### ISSUE TITLE
hps_isw_handoff/soc_system_hps_0

### ISSUE THREAD

**Issue by nuraalkhateeb** [sahandKashani/SoC-FPGA-Design-Guide#1]
Hi SahandKashani,

When following your tutorial and creating a new BSP (pg 55), the file soc_system_hps_0 does not exist in the directory? Is this a generic file that I can get from somewhere else?

Also, thank you for the tutorial. Well documented!

**Comment by sahandKashani** [comment]
Hi,

Just in case, "soc_system_hps_0" is actually a **directory**, not a file (in case you were looking specifically for a file).

The directory is normally automatically generated once you perform a full Quartus compilation.

**Comment by nuraalkhateeb** [comment]
Thank you! I was looking for it under your project and didn't realize that it did get automatically generated.

**Comment by sahandKashani** [comment]
Before you go too far in the tutorial (and risk frustration!), please read chapter 4 "Prerequisites" of the most recent version of the tutorial I just pushed (v 1.25).

Some of the tools used in the tutorial require licenses, and I've added some explanations about the various parts of the design that require these licenses. You would need to avoid those parts (or follow the free alternatives I list in the text) to avoid having any issues further down the road with the tutorial.

Sorry for not writing it earlier :(

**Comment by nuraalkhateeb** [comment]
Thank you for letting me know and for posting an updated version of the tutorial! I do not have the DS-5 license and will certainly need to look at the alternatives.
