### ISSUE TITLE
Eclipse-Nios .sopcinfo does not contain any CPU

### ISSUE THREAD

**Issue by Cryptum169** [sahandKashani/SoC-FPGA-Design-Guide#11]
Hi sahandKashiani

When going through the tutorial at Section 10 Using the Cyclone V - FPGA - Nios II - Bare - Metal, Eclipse-Nios2 is telling me that the .sopcinfo file does not contain any CPU. I made sure I have Nios in qsys and I opened the .sopcinfo file and searched for CPU and it did exist. I wonder if you have had a similar bug and what did you do to solve it. 

Thanks for the tutorial as well, this is the best one I've seen.

**Comment by sahandKashani** [comment]
Hi,
Yeah, I do occasionally get weird bugs like that (but not since a while). What I generally do is to delete all temporary files Quartus generates, open the .qsys file in Qsys, then **save** the file again.
After that, doing an Analysis & Synthesis and recreating the software project in Nios2EDS generally fixes the issue.

**Comment by Cryptum169** [comment]
Hi,

Thank you for the fast response! Do you mind specifying what temp files? I was afraid of destroying the project and only deleted the .sopcinfo file to generate it again. It was still giving me the message.

I also tried to open the .sopcinfo file from the demo project "Nios2AccessDDR3" and it's giving me the same message. So I'm wondering if it's eclipse's problem. Do you mind sharing whether you were using the lite version or pro version of quartus?

Thanks!

**Comment by Cryptum169** [comment]
Hi!
The issue seem to be the version of Quartus I was using. I downgraded from 17.1 to 17.0 and the message was gone. It appeared to be working now.
Thank you!

**Comment by sahandKashani** [comment]
Generally I delete all the following files (to be adapted to what your project name looks like:
```
rm -rf "c5_pin_model_dump.txt" \
       "db/" \
       "hps_isw_handoff/" \
       "hps_sdram_p0_all_pins.txt" \
       "incremental_db/" \
       "output_files/" \
       "soc_system.sopcinfo" \
       "soc_system/" \
       "${quartus_project_name}.qws"
```
But I'm glad you figured it out with the version number.

> Do you mind sharing whether you were using the lite version or pro version of quartus?

I always use the Lite version personally, but that doesn't allow you to convert an sof file containing a Nios II processor to an rbf file that can automatically be loaded at boot time. But if you don't want any automatic booting capabilities, then it isn't a problem to have the Lite version.
