### ISSUE TITLE
fdisk t   a2

### ISSUE THREAD

**Issue by nuraalkhateeb** [sahandKashani/SoC-FPGA-Design-Guide#2]
Hi Sahand,

When running the fdisk command, a2 does not exist. 

0  Empty           24  NEC DOS         81  Minix / old Lin bf  Solaris  
 1  FAT12           27  Hidden NTFS Win 82  Linux swap / So c1  DRDOS/sec (FAT-
 2  XENIX root      39  Plan 9          83  Linux           c4  DRDOS/sec (FAT-
 3  XENIX usr       3c  PartitionMagic  84  OS/2 hidden C:  c6  DRDOS/sec (FAT-
 4  FAT16 <32M      40  Venix 80286     85  Linux extended  c7  Syrinx  
 5  Extended        41  PPC PReP Boot   86  NTFS volume set da  Non-FS data  
 6  FAT16           42  SFS             87  NTFS volume set db  CP/M / CTOS / .
 7  HPFS/NTFS/exFAT 4d  QNX4.x          88  Linux plaintext de  Dell Utility  
 8  AIX             4e  QNX4.x 2nd part 8e  Linux LVM       df  BootIt  
 9  AIX bootable    4f  QNX4.x 3rd part 93  Amoeba          e1  DOS access  
 a  OS/2 Boot Manag 50  OnTrack DM      94  Amoeba BBT      e3  DOS R/O  
 b  W95 FAT32       51  OnTrack DM6 Aux 9f  BSD/OS          e4  SpeedStor  
 c  W95 FAT32 (LBA) 52  CP/M            a0  IBM Thinkpad hi eb  BeOS fs  
 e  W95 FAT16 (LBA) 53  OnTrack DM6 Aux a5  FreeBSD         ee  GPT  
 f  W95 Ext'd (LBA) 54  OnTrackDM6      a6  OpenBSD         ef  EFI (FAT-12/16/
10  OPUS            55  EZ-Drive        a7  NeXTSTEP        f0  Linux/PA-RISC b
11  Hidden FAT12    56  Golden Bow      a8  Darwin UFS      f1  SpeedStor  
12  Compaq diagnost 5c  Priam Edisk     a9  NetBSD          f4  SpeedStor  
14  Hidden FAT16 <3 61  SpeedStor       ab  Darwin boot     f2  DOS secondary  
16  Hidden FAT16    63  GNU HURD or Sys af  HFS / HFS+      fb  VMware VMFS  
17  Hidden HPFS/NTF 64  Novell Netware  b7  BSDI fs         fc  VMware VMKCORE 
18  AST SmartSleep  65  Novell Netware  b8  BSDI swap       fd  Linux raid auto
1b  Hidden W95 FAT3 70  DiskSecure Mult bb  Boot Wizard hid fe  LANstep  
1c  Hidden W95 FAT3 75  PC/IX           be  Solaris boot    ff  BBT  
1e  Hidden W95 FAT1 80  Old Minix      

these are the list codes available on my system when I run the command L to view the codes.

What code should I be using for the 3rd partition?

Thank you,
~Nora

**Comment by nuraalkhateeb** [comment]
Sorry, the codes didn't get pasted in a tabular format so it is a bit hard to read.

**Comment by sahandKashani** [comment]
Hi,

Partition identifier a2 does not correspond to any known partition. It is just the identifier that the preloader expects, so you can just type "a2" when prompted by fdisk. It will reply with something like the following line:

`Partition type (type L to list all types): a2`
`Changed type of partition 'W95 FAT32' to 'unknown'.`
`Command (m for help):`

**Comment by nuraalkhateeb** [comment]
Thanks! That's exactly what I got, that it is unknown. This led me to think that I was missing something.
