### ISSUE TITLE
HPS DDR3 Pin Assignments

### ISSUE THREAD

**Issue by nuraalkhateeb** [sahandKashani/SoC-FPGA-Design-Guide#6]
Hi Sahand,

I'm back on working on this and was wondering when I execute the TCL script for the HPS DDR3 pin assignments should I see location pin in pin planner for the HPS side?

**Comment by sahandKashani** [comment]
Hi,

No, you shouldn't see any HPS DDR3 pin assignments in the pin planner with the version of the `pin_assignment_xxx.tcl` scripts you have in the repository.

I had updated these scripts to include all HPS pins a few weeks back, but had forgotten to merge them into this guide. I just did that, so with the newest version of the `pin_assignment_xxx.tcl`files, you should find all HPS pins in the pin planner.

**Comment by nuraalkhateeb** [comment]
Thank you.

I'll check the updates.
